# Usa uma imagem oficial do Python como base. A versão 'slim' é mais leve.
FROM python:3.9-slim

# Define o diretório de trabalho dentro do container.
WORKDIR /app

# Copia o arquivo com a lista de dependências para dentro do container.
COPY requirements.txt .

# Instala as dependências listadas no requirements.txt.
# A instalação do cartopy pode levar alguns minutos.
RUN apt-get update && apt-get install -y libgeos-dev && \
    pip install --no-cache-dir -r requirements.txt

# Copia todos os outros arquivos (o app.py) para o diretório de trabalho.
COPY . .

# Expõe a porta 80, que é a porta padrão para serviços web no EasyPanel.
EXPOSE 80

# O comando que será executado quando o container iniciar.
# Ele inicia o servidor web Flask e o torna acessível a partir de outros serviços.
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]
